services:
  shipyard-rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: shipyard
      RABBITMQ_DEFAULT_PASS: shipyard
    ports:
      - "5672:5672"
      - "15672:15672"

  api-server:
    image: api-server:prod
  build-worker:
    image: build-worker:prod
  frontend:
    image: frontend:prod
  reverse-proxy:
    image: reverse-proxy:prod
